#!/usr/bin/env python3
"""
Bakes a third icon font from Google's Material Icons
(firmware/assets/fonts/MaterialIcons-Regular.ttf, Apache 2.0) for the new
bottom navigation dock (styling/UX pass, 2026-09-18).

Why a SEPARATE font from font_icons_20 (convert_icons.py) and
font_turn_icons_48 (convert_turn_icons.py): the dock spec calls for a
>=64x64px touch target per icon with the icon sitting above a text label -
a headline navigation element, not inline body text (font_icons_20's
purpose) and not quite the "dominant, at-a-glance" 48px scale of the turn
banner either. 32px is large enough to read clearly in a ~72px-tall dock
cell without needing the full 48px weight a turn instruction needs.

Icons baked (name: Material Icons codepoint -> dock destination), all
codepoints verified against firmware/assets/fonts/MaterialIcons-Regular.codepoints
directly (not guessed):
  home          0xE88A -> Telemetry (Speed/Drive/Status/Charging)
  battery_full  0xE1A4 -> BMS (Battery screen)
  map           0xE55B -> GPS (GPS/GPS NAV)
  bolt          0xEA0B -> Dyno (same glyph concept as font_icons_20's bolt,
                          but a fresh bake at this font's own size - fonts
                          don't share bitmap data across sizes)
  settings      0xE8B8 -> Settings

Same sparse-tiny-cmap fmt_txt format as convert_icons.py/convert_turn_icons.py
- see convert_icons.py's header comment for why. This script is a
parameterized copy of that generator rather than a shared import, matching
this project's existing one-script-per-asset convention.

Usage: python convert_dock_icons.py
"""
from pathlib import Path
from PIL import ImageFont

HERE = Path(__file__).parent
SRC_TTF = HERE / "fonts" / "MaterialIcons-Regular.ttf"
OUT_DIR = HERE.parent / "src"

ICON_SIZE = 32
BPP = 4
BPP_LEVELS = (1 << BPP) - 1
SYM = "font_dock_icons_32"
FALLBACK = "lv_font_montserrat_32"

ICONS = {
    "home": 0xE88A,
    "battery_full": 0xE1A4,
    "map": 0xE55B,
    "bolt": 0xEA0B,
    "settings": 0xE8B8,
}


def quantize(px):
    return round(px / 255 * BPP_LEVELS)


def main():
    font = ImageFont.truetype(str(SRC_TTF), ICON_SIZE)
    ascent, descent = font.getmetrics()
    line_height = ascent + descent
    base_line = descent

    names = list(ICONS.keys())
    codepoints = [ICONS[n] for n in names]

    glyphs = [dict(adv_w=0, box_w=0, box_h=0, ofs_x=0, ofs_y=0, bits=[])]  # id 0 reserved
    for cp in codepoints:
        ch = chr(cp)
        adv_w = round(font.getlength(ch) * 16)
        mask, (ox, oy) = font.getmask2(ch, mode="L")
        w, h = mask.size
        if w == 0 or h == 0:
            glyphs.append(dict(adv_w=adv_w, box_w=0, box_h=0, ofs_x=0, ofs_y=0, bits=[]))
            continue
        ofs_x = ox
        ofs_y = ascent - (oy + h)
        bits = [quantize(mask.getpixel((x, y))) for y in range(h) for x in range(w)]
        glyphs.append(dict(adv_w=adv_w, box_w=w, box_h=h, ofs_x=ofs_x, ofs_y=ofs_y, bits=bits))

    bitmap_bytes = bytearray()
    bit_buf = 0
    bit_cnt = 0
    bitmap_index = []
    for g in glyphs:
        if bit_cnt:
            bitmap_bytes.append((bit_buf << (8 - bit_cnt)) & 0xFF)
            bit_buf = 0
            bit_cnt = 0
        bitmap_index.append(len(bitmap_bytes))
        for level in g["bits"]:
            bit_buf = (bit_buf << BPP) | level
            bit_cnt += BPP
            while bit_cnt >= 8:
                bit_cnt -= 8
                bitmap_bytes.append((bit_buf >> bit_cnt) & 0xFF)
                bit_buf &= (1 << bit_cnt) - 1
    if bit_cnt:
        bitmap_bytes.append((bit_buf << (8 - bit_cnt)) & 0xFF)

    # Sparse tiny cmap - see convert_icons.py's comment on why unicode_list/
    # glyph_dsc must share the same sorted-by-codepoint order.
    range_start = min(codepoints)
    order = sorted(range(len(codepoints)), key=lambda i: codepoints[i])
    sorted_glyphs = [glyphs[0]] + [glyphs[i + 1] for i in order]
    sorted_bitmap_index = [bitmap_index[0]] + [bitmap_index[i + 1] for i in order]
    unicode_list = [codepoints[i] - range_start for i in order]
    icon_name_by_glyph_id = {i + 1: names[order[i]] for i in range(len(order))}

    out_c = OUT_DIR / f"{SYM}.c"
    out_h = OUT_DIR / f"{SYM}.h"

    with open(out_c, "w", newline="\n") as f:
        f.write(
            f"// Auto-generated by firmware/assets/convert_dock_icons.py from\n"
            f"// MaterialIcons-Regular.ttf - do not hand-edit.\n"
            f"#include \"{SYM}.h\"\n\n"
        )
        f.write("static const uint8_t glyph_bitmap[] = {\n")
        for i in range(0, len(bitmap_bytes), 16):
            chunk = bitmap_bytes[i:i + 16]
            f.write("    " + ",".join(f"0x{x:02X}" for x in chunk) + ",\n")
        f.write("};\n\n")

        f.write("static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {\n")
        for i, g in enumerate(sorted_glyphs):
            bi = sorted_bitmap_index[i]
            name_comment = f" // {icon_name_by_glyph_id[i]}" if i in icon_name_by_glyph_id else ""
            f.write(
                f"    {{.bitmap_index = {bi}, .adv_w = {g['adv_w']}, "
                f".box_w = {g['box_w']}, .box_h = {g['box_h']}, "
                f".ofs_x = {g['ofs_x']}, .ofs_y = {g['ofs_y']}}},{name_comment}\n"
            )
        f.write("};\n\n")

        f.write(
            f"static const uint16_t unicode_list[] = {{ {', '.join(str(u) for u in unicode_list)} }};\n\n"
            "static const lv_font_fmt_txt_cmap_t cmaps[] = {\n"
            "    {\n"
            f"        .range_start = 0x{range_start:04X}, "
            f".range_length = 0x{(max(codepoints) - range_start + 1):04X},\n"
            "        .glyph_id_start = 1,\n"
            "        .unicode_list = unicode_list, .glyph_id_ofs_list = NULL,\n"
            f"        .list_length = {len(unicode_list)},\n"
            "        .type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY\n"
            "    }\n"
            "};\n\n"
        )

        f.write(
            "static lv_font_fmt_txt_glyph_cache_t cache;\n\n"
            "static const lv_font_fmt_txt_dsc_t font_dsc = {\n"
            "    .glyph_bitmap = glyph_bitmap,\n"
            "    .glyph_dsc = glyph_dsc,\n"
            "    .cmaps = cmaps,\n"
            "    .kern_dsc = NULL,\n"
            "    .kern_scale = 0,\n"
            "    .cmap_num = 1,\n"
            "    .bpp = 4,\n"
            "    .kern_classes = 0,\n"
            "    .bitmap_format = 0,\n"
            "    .cache = &cache\n"
            "};\n\n"
            f"const lv_font_t {SYM} = {{\n"
            "    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,\n"
            "    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,\n"
            f"    .line_height = {line_height},\n"
            f"    .base_line = {base_line},\n"
            "    .subpx = LV_FONT_SUBPX_NONE,\n"
            "    .underline_position = -1,\n"
            "    .underline_thickness = 1,\n"
            "    .dsc = &font_dsc,\n"
            f"    .fallback = &{FALLBACK}\n"
            "};\n"
        )

    utf8_defines = []
    for name, cp in ICONS.items():
        utf8 = chr(cp).encode("utf-8")
        literal = "".join(f"\\x{b:02X}" for b in utf8)
        utf8_defines.append(f'#define DOCK_ICON_{name.upper()} "{literal}"')

    with open(out_h, "w", newline="\n") as f:
        f.write(
            "#pragma once\n\n"
            "// Auto-generated by firmware/assets/convert_dock_icons.py from Google's\n"
            "// Material Icons (Apache 2.0). 5 icons only, sparse cmap, standalone use\n"
            "// (NOT chained through body text, unlike font_icons_20) - see this file's\n"
            "// .c header comment for the codepoint-to-destination mapping. Use as a\n"
            "// label's whole text, e.g. lv_label_set_text(iconLabel, DOCK_ICON_HOME).\n\n"
            "#include \"lvgl.h\"\n\n"
            f"extern const lv_font_t {SYM};\n\n"
            "// Icon codepoints, ready to use directly as label text:\n"
            + "\n".join(utf8_defines) + "\n"
        )

    print(f"Wrote {out_c.name}, {out_h.name}: {len(sorted_glyphs)} glyphs "
          f"({', '.join(names)}), {len(bitmap_bytes)} bytes bitmap data")


if __name__ == "__main__":
    main()
