#!/usr/bin/env python3
"""
Bakes a second, larger icon font from Google's Material Icons
(firmware/assets/fonts/MaterialIcons-Regular.ttf, Apache 2.0) for the GPS
NAV screen's turn-instruction banner (component 5 of the IceNav-v3-based
nav screen rebuild, 2026-09-16).

Why a SEPARATE font from font_icons_20 (convert_icons.py): that one is
deliberately sized/chained for inline use inside 16px panel-title labels
(CLAUDE.md: "Only 16px chains through the icon font"). A turn banner is a
headline UI element, not inline body text, and needs to read at a glance -
same "large, dominant" visual language as the dyno screen's 48px hero
timer numeral (font_montserrat_extrabold_48). So this bakes its own
48px icon font instead of trying to stretch font_icons_20 past the size
it was actually designed for.

Icons baked (name: Material Icons codepoint -> meaning here):
  straight          0xEB95 -> no turn coming up / go straight
  turn_left         0xEBA6 -> soft left (15-60 degrees)
  turn_right        0xEBAB -> soft right (15-60 degrees)
  turn_sharp_left   0xEBA7 -> hard left (60+ degrees)
  turn_sharp_right  0xEBAA -> hard right (60+ degrees)
  flag              0xE153 -> arrived / end of route
No off-track icon - that's a rarer edge state, shown as text
("OFF ROUTE") rather than justifying a 7th glyph.

Same sparse-tiny-cmap fmt_txt format as convert_icons.py - see that
script's header comment for why (a handful of codepoints scattered across
Material Icons' space, not a contiguous range). This script is a
parameterized copy of convert_icons.py's generator rather than a shared
import, matching this project's existing one-script-per-asset convention
(convert_font.py/convert_icons.py/convert_logo.py are all standalone).

Usage: python convert_turn_icons.py
"""
from pathlib import Path
from PIL import ImageFont

HERE = Path(__file__).parent
SRC_TTF = HERE / "fonts" / "MaterialIcons-Regular.ttf"
OUT_DIR = HERE.parent / "src"

ICON_SIZE = 48
BPP = 4
BPP_LEVELS = (1 << BPP) - 1
SYM = "font_turn_icons_48"
FALLBACK = "lv_font_montserrat_48"

ICONS = {
    "straight": 0xEB95,
    "turn_left": 0xEBA6,
    "turn_right": 0xEBAB,
    "turn_sharp_left": 0xEBA7,
    "turn_sharp_right": 0xEBAA,
    "flag": 0xE153,
}


def quantize(px):
    return round(px / 255 * BPP_LEVELS)


def main():
    font = ImageFont.truetype(str(SRC_TTF), ICON_SIZE)
    ascent, descent = font.getmetrics()
    line_height = ascent + descent
    base_line = descent

    names = list(ICONS.keys())
    codepoints = [ICONS[n] for n in names]

    glyphs = [dict(adv_w=0, box_w=0, box_h=0, ofs_x=0, ofs_y=0, bits=[])]  # id 0 reserved
    for cp in codepoints:
        ch = chr(cp)
        adv_w = round(font.getlength(ch) * 16)
        mask, (ox, oy) = font.getmask2(ch, mode="L")
        w, h = mask.size
        if w == 0 or h == 0:
            glyphs.append(dict(adv_w=adv_w, box_w=0, box_h=0, ofs_x=0, ofs_y=0, bits=[]))
            continue
        ofs_x = ox
        ofs_y = ascent - (oy + h)
        bits = [quantize(font.getmask2(ch, mode="L")[0].getpixel((x, y)))
                for y in range(h) for x in range(w)]
        glyphs.append(dict(adv_w=adv_w, box_w=w, box_h=h, ofs_x=ofs_x, ofs_y=ofs_y, bits=bits))

    bitmap_bytes = bytearray()
    bit_buf = 0
    bit_cnt = 0
    bitmap_index = []
    for g in glyphs:
        if bit_cnt:
            bitmap_bytes.append((bit_buf << (8 - bit_cnt)) & 0xFF)
            bit_buf = 0
            bit_cnt = 0
        bitmap_index.append(len(bitmap_bytes))
        for level in g["bits"]:
            bit_buf = (bit_buf << BPP) | level
            bit_cnt += BPP
            while bit_cnt >= 8:
                bit_cnt -= 8
                bitmap_bytes.append((bit_buf >> bit_cnt) & 0xFF)
                bit_buf &= (1 << bit_cnt) - 1
    if bit_cnt:
        bitmap_bytes.append((bit_buf << (8 - bit_cnt)) & 0xFF)

    range_start = min(codepoints)
    order = sorted(range(len(codepoints)), key=lambda i: codepoints[i])
    sorted_glyphs = [glyphs[0]] + [glyphs[i + 1] for i in order]
    sorted_bitmap_index = [bitmap_index[0]] + [bitmap_index[i + 1] for i in order]
    unicode_list = [codepoints[i] - range_start for i in order]
    icon_name_by_glyph_id = {i + 1: names[order[i]] for i in range(len(order))}

    out_c = OUT_DIR / f"{SYM}.c"
    out_h = OUT_DIR / f"{SYM}.h"

    with open(out_c, "w", newline="\n") as f:
        f.write(
            f"// Auto-generated by firmware/assets/convert_turn_icons.py from\n"
            f"// MaterialIcons-Regular.ttf - do not hand-edit.\n"
            f"#include \"{SYM}.h\"\n\n"
        )
        f.write("static const uint8_t glyph_bitmap[] = {\n")
        for i in range(0, len(bitmap_bytes), 16):
            chunk = bitmap_bytes[i:i + 16]
            f.write("    " + ",".join(f"0x{x:02X}" for x in chunk) + ",\n")
        f.write("};\n\n")

        f.write("static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {\n")
        for i, g in enumerate(sorted_glyphs):
            bi = sorted_bitmap_index[i]
            name_comment = f" // {icon_name_by_glyph_id[i]}" if i in icon_name_by_glyph_id else ""
            f.write(
                f"    {{.bitmap_index = {bi}, .adv_w = {g['adv_w']}, "
                f".box_w = {g['box_w']}, .box_h = {g['box_h']}, "
                f".ofs_x = {g['ofs_x']}, .ofs_y = {g['ofs_y']}}},{name_comment}\n"
            )
        f.write("};\n\n")

        f.write(
            f"static const uint16_t unicode_list[] = {{ {', '.join(str(u) for u in unicode_list)} }};\n\n"
            "static const lv_font_fmt_txt_cmap_t cmaps[] = {\n"
            "    {\n"
            f"        .range_start = 0x{range_start:04X}, "
            f".range_length = 0x{(max(codepoints) - range_start + 1):04X},\n"
            "        .glyph_id_start = 1,\n"
            "        .unicode_list = unicode_list, .glyph_id_ofs_list = NULL,\n"
            f"        .list_length = {len(unicode_list)},\n"
            "        .type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY\n"
            "    }\n"
            "};\n\n"
        )

        f.write(
            "static lv_font_fmt_txt_glyph_cache_t cache;\n\n"
            "static const lv_font_fmt_txt_dsc_t font_dsc = {\n"
            "    .glyph_bitmap = glyph_bitmap,\n"
            "    .glyph_dsc = glyph_dsc,\n"
            "    .cmaps = cmaps,\n"
            "    .kern_dsc = NULL,\n"
            "    .kern_scale = 0,\n"
            "    .cmap_num = 1,\n"
            "    .bpp = 4,\n"
            "    .kern_classes = 0,\n"
            "    .bitmap_format = 0,\n"
            "    .cache = &cache\n"
            "};\n\n"
            f"const lv_font_t {SYM} = {{\n"
            "    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,\n"
            "    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,\n"
            f"    .line_height = {line_height},\n"
            f"    .base_line = {base_line},\n"
            "    .subpx = LV_FONT_SUBPX_NONE,\n"
            "    .underline_position = -1,\n"
            "    .underline_thickness = 1,\n"
            "    .dsc = &font_dsc,\n"
            f"    .fallback = &{FALLBACK}\n"
            "};\n"
        )

    utf8_defines = []
    for name, cp in ICONS.items():
        utf8 = chr(cp).encode("utf-8")
        literal = "".join(f"\\x{b:02X}" for b in utf8)
        utf8_defines.append(f'#define TURN_ICON_{name.upper()} "{literal}"')

    with open(out_h, "w", newline="\n") as f:
        f.write(
            "#pragma once\n\n"
            "// Auto-generated by firmware/assets/convert_turn_icons.py from\n"
            "// Google's Material Icons (Apache 2.0). 6 icons, sparse cmap - see\n"
            "// this file's .c header comment for the codepoint-to-meaning mapping\n"
            "// and why a separate font from font_icons_20. Use standalone (not\n"
            "// chained through body text) e.g.\n"
            "//   lv_label_set_text(turnIconLabel, TURN_ICON_STRAIGHT);\n"
            "//   lv_obj_set_style_text_font(turnIconLabel, &font_turn_icons_48, ...);\n"
            "// (TURN_ICON_* is a raw UTF-8 byte-string literal, not a codepoint\n"
            "// constant).\n\n"
            "#include \"lvgl.h\"\n\n"
            f"extern const lv_font_t {SYM};\n\n"
            "// Icon codepoints, ready to use directly:\n"
            + "\n".join(utf8_defines) + "\n"
        )

    print(f"Wrote {out_c.name}, {out_h.name}: {len(sorted_glyphs)} glyphs "
          f"({', '.join(names)}), {len(bitmap_bytes)} bytes bitmap data")


if __name__ == "__main__":
    main()
