#!/usr/bin/env python3
"""
Converts firmware/assets/SCOUT.png into an LVGL 8.x LV_IMG_CF_TRUE_COLOR_ALPHA
C image descriptor (firmware/src/img_scout_logo.c/.h), for the Splash/Clock
screen (design-review "Scout brand mark" pass, 2026-09-14 - see
waveshare-dash-build.md).

Why hand-rolled instead of LVGL's own online/offline image converter: this
project's LV_USE_PNG is 0 (see lv_conf.h - deliberately, same reasoning as
the deleted custom fonts), so the PNG has to become a compile-time C array
either way; writing the converter directly gives full control over the
alpha-keying step below, which the stock converter doesn't do.

Kept at native resolution (380x142, no resize) - the source is a raster
logo, not vector, and upscaling a script/cursive font blurs it. Downscaling
would work but isn't needed at this size on an 800x480 display.

Alpha-keys the logo's flat black background to transparent (luminance
ramp, not a hard cutoff, so the cursive letters' anti-aliased edges blend
smoothly into whichever theme background is behind them - day or night -
instead of carrying a visible black rectangle). Calibrated against this
specific file's actual luminance histogram (checked before picking
thresholds, not guessed): a hard bimodal split at ~0 and ~250 with a small
smear of edge-antialiasing pixels in between, so LOW=15/HIGH=235 cover the
real edge pixels without clipping the crisp black/white regions.

Pixel format confirmed against this project's actual LVGL build config
(LV_COLOR_DEPTH=16, LV_COLOR_16_SWAP=0 - see ui.c's compile-time asserts)
and LVGL's own lv_img_buf.h: LV_IMG_CF_TRUE_COLOR_ALPHA at 16-bit color
depth is 3 bytes/pixel - 2 bytes RGB565 (little-endian, since SWAP=0)
followed by 1 alpha byte. Not assumed - read directly from LVGL's own
source before writing this.

Usage: python convert_logo.py
(Run manually when the source PNG changes - not part of the PlatformIO
build, same as this project has no other asset-pipeline build step.)
"""
import struct
from pathlib import Path
from PIL import Image

HERE = Path(__file__).parent
SRC_PNG = HERE / "SCOUT.png"
OUT_C = HERE.parent / "src" / "img_scout_logo.c"
OUT_H = HERE.parent / "src" / "img_scout_logo.h"

ALPHA_LOW = 15   # luminance at/below this -> fully transparent
ALPHA_HIGH = 235  # luminance at/above this -> fully opaque


def alpha_for_luminance(lum: float) -> int:
    if lum <= ALPHA_LOW:
        return 0
    if lum >= ALPHA_HIGH:
        return 255
    return round((lum - ALPHA_LOW) / (ALPHA_HIGH - ALPHA_LOW) * 255)


def main():
    im = Image.open(SRC_PNG).convert("RGB")
    w, h = im.size
    px = im.load()

    out = bytearray()
    for y in range(h):
        for x in range(w):
            r, g, b = px[x, y]
            lum = 0.299 * r + 0.587 * g + 0.114 * b
            a = alpha_for_luminance(lum)
            # RGB565 pack, then little-endian byte order (LV_COLOR_16_SWAP=0)
            rgb565 = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
            out += struct.pack("<H", rgb565)
            out.append(a)

    assert len(out) == w * h * 3, f"expected {w*h*3} bytes, got {len(out)}"

    # C source - byte array + lv_img_dsc_t, same shape LVGL's own image
    # converter tool emits (LV_IMG_CF_TRUE_COLOR_ALPHA, header bitfields).
    with open(OUT_C, "w", newline="\n") as f:
        f.write(
            "// Auto-generated by firmware/assets/convert_logo.py from SCOUT.png\n"
            "// - do not hand-edit. Re-run the script if the source PNG changes.\n"
            "#include \"img_scout_logo.h\"\n\n"
            f"static const uint8_t scout_logo_map[] = {{\n"
        )
        for i in range(0, len(out), 16):
            chunk = out[i:i + 16]
            f.write("    " + ",".join(f"0x{b:02X}" for b in chunk) + ",\n")
        f.write(
            "};\n\n"
            "const lv_img_dsc_t img_scout_logo = {\n"
            "    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,\n"
            "    .header.always_zero = 0,\n"
            "    .header.reserved = 0,\n"
            f"    .header.w = {w},\n"
            f"    .header.h = {h},\n"
            f"    .data_size = {len(out)},\n"
            "    .data = scout_logo_map,\n"
            "};\n"
        )

    with open(OUT_H, "w", newline="\n") as f:
        f.write(
            "#pragma once\n\n"
            "// Auto-generated by firmware/assets/convert_logo.py from SCOUT.png -\n"
            "// see img_scout_logo.c's header comment for the conversion details\n"
            "// (alpha-keyed black background, RGB565+alpha, native 380x142 resolution).\n"
            "// Used on the Splash/Clock screen only - CLAUDE.md's rule that the splash\n"
            "// graphic never appears as a placeholder on any other screen still applies.\n\n"
            "#include \"lvgl.h\"\n\n"
            "extern const lv_img_dsc_t img_scout_logo;\n"
        )

    print(f"Wrote {OUT_C} and {OUT_H}: {w}x{h}, {len(out)} bytes image data")


if __name__ == "__main__":
    main()
