#pragma once

// Auto-generated by firmware/assets/convert_font.py - ExtraBold-weight
// Montserrat at 24px, baked as a real bold bitmap font (LVGL's bundled
// Montserrat fonts are regular-weight only). ASCII 0x20-0x7E + degree sign
// (0xB0) only - falls back to the regular-weight font of the same size for
// any other codepoint (the LV_SYMBOL_* icons), see this file's .c header
// comment for why that needs no extra icon-font asset.

#include "lvgl.h"

extern const lv_font_t font_montserrat_extrabold_24;
