#pragma once

// Auto-generated by firmware/assets/convert_dock_icons.py from Google's
// Material Icons (Apache 2.0). 5 icons only, sparse cmap, standalone use
// (NOT chained through body text, unlike font_icons_20) - see this file's
// .c header comment for the codepoint-to-destination mapping. Use as a
// label's whole text, e.g. lv_label_set_text(iconLabel, DOCK_ICON_HOME).

#include "lvgl.h"

extern const lv_font_t font_dock_icons_32;

// Icon codepoints, ready to use directly as label text:
#define DOCK_ICON_HOME "\xEE\xA2\x8A"
#define DOCK_ICON_BATTERY_FULL "\xEE\x86\xA4"
#define DOCK_ICON_MAP "\xEE\x95\x9B"
#define DOCK_ICON_BOLT "\xEE\xA8\x8B"
#define DOCK_ICON_SETTINGS "\xEE\xA2\xB8"
