#pragma once

// Auto-generated by firmware/assets/convert_turn_icons.py from
// Google's Material Icons (Apache 2.0). 6 icons, sparse cmap - see
// this file's .c header comment for the codepoint-to-meaning mapping
// and why a separate font from font_icons_20. Use standalone (not
// chained through body text) e.g.
//   lv_label_set_text(turnIconLabel, TURN_ICON_STRAIGHT);
//   lv_obj_set_style_text_font(turnIconLabel, &font_turn_icons_48, ...);
// (TURN_ICON_* is a raw UTF-8 byte-string literal, not a codepoint
// constant).

#include "lvgl.h"

extern const lv_font_t font_turn_icons_48;

// Icon codepoints, ready to use directly:
#define TURN_ICON_STRAIGHT "\xEE\xAE\x95"
#define TURN_ICON_TURN_LEFT "\xEE\xAE\xA6"
#define TURN_ICON_TURN_RIGHT "\xEE\xAE\xAB"
#define TURN_ICON_TURN_SHARP_LEFT "\xEE\xAE\xA7"
#define TURN_ICON_TURN_SHARP_RIGHT "\xEE\xAE\xAA"
#define TURN_ICON_FLAG "\xEE\x85\x93"
