#pragma once

// Auto-generated by firmware/assets/convert_icons.py from Google's
// Material Icons (Apache 2.0). 5 icons only, sparse cmap - see this
// file's .c header comment for the codepoint-to-meaning mapping and
// why these specific icons. Use as e.g.
//   lv_label_set_text_fmt(label, "%s POWER", ICON_BOLT);
// (ICON_* is a raw UTF-8 byte-string literal, not a codepoint constant).

#include "lvgl.h"

extern const lv_font_t font_icons_20;

// Icon codepoints, ready to use directly in a format string:
#define ICON_BOLT "\xEE\xA8\x8B"
#define ICON_THERMOSTAT "\xEF\x81\xB6"
#define ICON_LOCATION_ON "\xEE\x83\x88"
#define ICON_NAVIGATION "\xEE\x95\x9D"
#define ICON_SPEED "\xEE\xA7\xA4"
