#pragma once

// Auto-generated by firmware/assets/convert_logo.py from SCOUT.png -
// see img_scout_logo.c's header comment for the conversion details
// (alpha-keyed black background, RGB565+alpha, native 380x142 resolution).
// Used on the Splash/Clock screen only - CLAUDE.md's rule that the splash
// graphic never appears as a placeholder on any other screen still applies.

#include "lvgl.h"

extern const lv_img_dsc_t img_scout_logo;
