// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    // Splash/Clock is the eager boot screen (2026-09-14, corrected same
    // day it was built - "just boots to speedo" feedback from Rob made
    // clear a screen literally named "splash" should be the first thing
    // shown, not a regular mid-chain screen). It auto-advances to Speed
    // after a few seconds - see ui_splashScreen.c's one-shot timer.
    ui_splashScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_splashScreen);
}

void ui_destroy(void)
{
    ui_speedScreen_screen_destroy();
    ui_driveScreen_screen_destroy();
    ui_statusScreen_screen_destroy();
    ui_batteryScreen_screen_destroy();
    ui_chargingScreen_screen_destroy();
    ui_gpsScreen_screen_destroy();
    ui_navScreen_screen_destroy();
    ui_dynoLiveScreen_screen_destroy();
    ui_dynoResultsScreen_screen_destroy();
    ui_settingsScreen_screen_destroy();
    ui_splashScreen_screen_destroy();
}
