// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme.h"


///////////////////// SCREENS ////////////////////

#include "ui_speedScreen.h"
#include "ui_driveScreen.h"
#include "ui_statusScreen.h"
#include "ui_batteryScreen.h"
#include "ui_chargingScreen.h"
#include "ui_gpsScreen.h"
#include "ui_navScreen.h"
#include "ui_dynoLiveScreen.h"
#include "ui_dynoResultsScreen.h"
#include "ui_settingsScreen.h"
#include "ui_splashScreen.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// FONTS
// uaDASH's original custom fonts (Indicator/-Label/Label/RPM/Speed) were
// removed 2026-09-13 per CLAUDE.md's typography rule - stylized SuperBrigade/
// Fussion racing-dashboard faces that don't match this project's direction
// (and are almost certainly what read as "italic" before this migration).
//
// 2026-09-14: every screen now uses hand-baked ExtraBold-weight Montserrat
// (font_montserrat_extrabold_16/24/32/48, firmware/assets/convert_font.py)
// instead of LVGL's bundled REGULAR-weight lv_font_montserrat_* - "much
// bolder/chunkier fonts... for readability" per Rob. LVGL ships no bold
// variant of its built-in fonts, so getting real bold weight meant baking
// new bitmap fonts from an actual bold TTF (see that script's header for
// the format details and why it's hand-rolled rather than LVGL's own
// lv_font_conv tool). Each one falls back to the original regular-weight
// lv_font_montserrat_* of the same size for any codepoint it doesn't cover
// (specifically the LV_SYMBOL_* icons from the earlier icons pass) - both
// font sets stay linked in, not a full replacement.
#include "font_montserrat_extrabold_16.h"
#include "font_montserrat_extrabold_24.h"
#include "font_montserrat_extrabold_32.h"
#include "font_montserrat_extrabold_48.h"

// 2026-09-14: small custom icon set (bolt/thermostat/location_on/
// navigation/speed, firmware/assets/convert_icons.py, from Google's
// Material Icons) for panel titles that benefit from an at-a-glance
// pictogram alongside their text - "what else were you thinking" pass.
// font_montserrat_extrabold_16's .fallback chains through this icon font
// before reaching lv_font_montserrat_16, so any 16px label can mix bold
// text + one of these icons + LV_SYMBOL_* glyphs with no extra widget -
// see convert_font.py's header comment for why that chain is safe.
// Use like: lv_label_set_text(titleLabel, ICON_BOLT " POWER");
#include "font_icons_20.h"

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
